### ISSUE TITLE
AES in this project is harmfull

### ISSUE THREAD

**Issue by ex3ndr** [altoo-ag/akka-kryo-serialization#108]
You are using AES without authentication in all your examples. This should be reimplemented to use manual authentication with simple HMAC or use authenticated modes like AEAD. While it could be configured it still everywhere in the documentation and should be replaced to avoid security-related problems.

Thanks.

**Comment by danischroeter** [comment]
Hi @ex3ndr 
Thx a lot for the input! Do you actively use the AES encryption?
Would you mind adapting the documentation and create a pull request?

**Comment by nvollmar** [comment]
So the suggestion would be either adding explicit HMAC or using `"AES/CCM/PKCS5Padding"` instead of plain CBC?

**Comment by nvollmar** [comment]
See https://proandroiddev.com/security-best-practices-symmetric-encryption-with-aes-in-java-and-android-part-2-b3b80e99ad36
