### ISSUE TITLE
Cannot find version 0.5.1 of akka-kryo-serialization_2.11 on Maven Central Respository

### ISSUE THREAD

**Issue by royalan** [altoo-ag/akka-kryo-serialization#109]

**Comment by luben** [comment]
please use 0.5.0  - they are functionally equivalent.

**Comment by ivanopagano** [comment]
It's alright but please, kindly update the README file to avoid consistently confusing newcomers

**Comment by notxcain** [comment]
Please publish a version for both 2.11 and 2.12, because when you cross-compile your project it becomes very inconvenient.

**Comment by easel** [comment]
I've cross-built the 0.5.3 snapshot code against Akka 2.5 and scala 2.11/2.12. Binaries are on bintray at https://bintray.com/7thsense/maven/akka-kryo-serialization if you want them.

**Comment by nvollmar** [comment]
closing this as we will provide new artifacts soon
