### ISSUE TITLE
Implement also the ByteBufferSerializer interface

### ISSUE THREAD

**Issue by luben** [altoo-ag/akka-kryo-serialization#112]
... to be used with the new (experimental) remoting transport:

http://doc.akka.io/docs/akka/2.4/scala/remoting-artery.html#ByteBuffer_based_serialization

**Comment by luben** [comment]
I am currently working on it. The base case is already implemented. I have also to cover the transformations (if applicable)

**Comment by luben** [comment]
The artery transport is leaking a lot of memory in my case. I can't decide if our code contributes to the akka leaks. I'll give it a try again after next akka release

**Comment by danischroeter** [comment]
hi @luben
Using the ByteBufferSerializer is still a topic ;)
https://doc.akka.io/docs/akka/current/remoting-artery.html?language=scala#ByteBuffer_based_serialization
Are you interested in trying with the latest versions or handing over your work in progress?

**Comment by luben** [comment]
Hi @danischroeter ,

Thanks for taking the responsibility of the library.

I didn't finished my work on adding the support for ByteBuffers. I have since moved on so I don't think I will finish it.

**Comment by danischroeter** [comment]
Thx for the quick response!
Sure - fair enough. We're happy to continue the great work of you guys!

**Comment by armanbilge** [comment]
What is the status of this issue, help-wanted?

**Comment by nvollmar** [comment]
Implemented by #255
