### ISSUE TITLE
ASM conflict and kryo-shaded

### ISSUE THREAD

**Issue by pacien** [altoo-ag/akka-kryo-serialization#113]
Hello,

Using `akka-kryo-serialization` in a (Play) project already using a different version of the `asm` library causes unserialization errors.

This issue can be mitigated by using `kryo-shaded` instead of `kryo`, which includes its own `asm` jar.

Would it be possible to publish `akka-kryo-serialization` (or a different alternative package) depending on `kryo-shaded` instead of `kryo`?

**Comment by protheusfr** [comment]
+1, akka & play comping from the same company and are logically used together, the usage of Kryo serialization framework could be natural in this context.

**Comment by romix** [comment]
In general, I'm not opposed to this idea. Any volunteers to submit a PR for this feature?

**Comment by nvollmar** [comment]
we'll be depending on `kryo-shaded` with the next release
