### ISSUE TITLE
Please build for Akka 2.5.0

### ISSUE THREAD

**Issue by aginiewicz** [altoo-ag/akka-kryo-serialization#116]
It would be great to have a release for Akka 2.5.0. Thanks for your great work!

**Comment by synox** [comment]
Does this mean Akka 2.5 can currently not be used with akka-kryo-serialization?

**Comment by ktoso** [comment]
Please note that Akka 2.5/2.4 are actually binary compatible - i.e. 2.5 is backwards compatible with 2.4, so using this library with 2.5 should "just work" ™ :-) More info: http://akka.io/news/2017/04/13/akka-2.5.0-released.html and the compatibility rules explained: http://doc.akka.io/docs/akka/2.5/common/binary-compatibility-rules.html so you could most likely just use this library with 2.5.x I think.

Let's update nevertheless... I checked locally and all tests pass so it's a question of what to call the version that would ship compiled against 2.5?

**Comment by Enalmada** [comment]
I just made a quick hack for akka 2.5.17 because I updated PlayFramework version which latest version now uses 2.5.17 and was getting strong warnings about how all versions of akka across modules needs to be the same.  Just incase it helps someone until this official project gets updated:
    "com.github.enalmada" %% "akka-kryo-serialization" % "0.5.3"

**Comment by danischroeter** [comment]
the latest version is built against akka 2.5
btw if you know the versions are indeed compatible you can ignore the dependency to akka from the kryo serializer with `ExclusionRule("com.typesafe.akka", "akka-actor_2.12")`
