### ISSUE TITLE
Smaller ids lead to smaller sizes of serialized representations?

### ISSUE THREAD

**Issue by gtykhonov** [altoo-ag/akka-kryo-serialization#141]
From readme.md: 

>       # Define mappings from a fully qualified class name to a numeric id.
>       # Smaller ids lead to smaller sizes of serialized representations.
>       #
>       # This section is:
>       # - mandatory for idstrategy="explicit"
>       # - ignored   for idstrategy="default"
>       # - optional  for incremental and automatic
>       #
>       # The smallest possible id should start at 20 (or even higher), because
>       # ids below it are used by Kryo internally e.g. for built-in Java and
>       # Scala types
>       mappings {
>           "package1.name1.className1" = 20,
>           "package2.name2.className2" = 21
>       }

Could you clarify?

We're currently reorganizing our class to id mappings for kryo into something like this:
```
mappings {
 //Java 40-999
"package1.class1" = 40,
"package2.class2" = 41
...
//Common 1000-1999
...
//Module1 2000-2999
...
//Module2 3000-3999
...
}
```
Would the size of serialized representations be significantly larger compared to ranges like 0-99, 100-199, etc? How much is the serialized representations size affected by id size?

Thanks.

**Comment by nvollmar** [comment]
The id is passed as int to kryo, so I figure the range does not make any difference.
