### ISSUE TITLE
Map of Map deserialization

### ISSUE THREAD

**Issue by ifif14** [altoo-ag/akka-kryo-serialization#144]
Following fails without any further explaination

`Map().withDefaultValue(Map().withDefaultValue(BigDecimal(0)))`

> Failed to deserialize message from [] with serializer id [123454323] and manifest []. java.lang.NullPointerException

Any ideas?

**Comment by ifif14** [comment]
More precisely this fails: Map().withDefaultValue(BigDecimal(0))

**Comment by nvollmar** [comment]
Seems to work with
```
kryo.addDefaultSerializer(classOf[scala.collection.Map[_, _]], classOf[ScalaImmutableAbstractMapSerializer])
```

**Comment by nvollmar** [comment]
Closing the issue for now - please report if this does not solve your problem
