### ISSUE TITLE
document and test akka compatiblity

### ISSUE THREAD

**Issue by danischroeter** [altoo-ag/akka-kryo-serialization#151]
We know *(guess/assume) we are compatible to akka 2.4,2.5 and even 2.6
->add tests against different versions of akka and state the compatiblity in the doc

**Comment by nvollmar** [comment]
We cannot compile against 2.4 anymore due to changes in Akka TestKit (expectNoMsg has been deprecated and replacement expectNoMessage is not available in 2.4).
