### ISSUE TITLE
adapt to altoo-ag and publish to sonatype

### ISSUE THREAD

**Issue by danischroeter** [altoo-ag/akka-kryo-serialization#153]
we need to 
- [x] change the artifact groupid to io.altoo (#162)
- [x] change the packages to io.altoo (#162)
- [x] register with sonatype and get agreement
- [x] publish to sonatype/maven1
- [x] create a guide on how to migrate
- [x] move config root out of akka namespace

all this while maintaining as minimal config changes necessary as possible...
although we might as well really cleanup the config see #63 and try to implement convention over configuration - but completely break the current config...

see
https://www.scala-sbt.org/1.x/docs/Using-Sonatype.html

**Comment by danischroeter** [comment]
duplicates #43

**Comment by nvollmar** [comment]
[] change config root

**Comment by danischroeter** [comment]
package:
io.altoo.akka.serialization.kryo

drop standalone scala support/package since this is tied to deeply to akka anyway - however if anybody wants he could use the integrated serializers...

**Comment by danischroeter** [comment]
sonatype done with RC4 - ready to do the 1.0.0 once we are done testing...
