### ISSUE TITLE
Encountered unregistered class ID

### ISSUE THREAD

**Issue by idar** [altoo-ag/akka-kryo-serialization#16]
Hi 

I get this exception when sending messages across two nodes. 
we use deault strategy and we have logged that kryo uses writeClassAndObject and readClassAndObject.

This is in a akkacluser and there are messages going back and fort with java serialization and google protbuf. 

any ideas?

AkkaConfig:
    actor {
        provider = "akka.cluster.ClusterActorRefProvider"

```
     serializers {
         java = "akka.serialization.JavaSerializer"
         proto = "akka.remote.serialization.ProtobufSerializer"
         kryo =  "com.romix.akka.serialization.kryo.KryoSerializer"
     }

     serialization-bindings {
         "no.ks.eventstore2.Event" = kryo
     }

     kryo{
        type = "graph"
        idstrategy = "default"
        serializer-pool-size = 16
        buffer-size = 4096
        use-manifests = false
        implicit-registration-logging = true
        kryo-trace = false
        kryo-custom-serializer-init = "no.ks.KryoInit"
     }
}

extensions = ["com.romix.akka.serialization.kryo.KryoSerializationExtension$"]
```

exception:
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 720389982
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:656)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
        at com.romix.akka.serialization.kryo.KryoBasedSerializer.fromBinary(KryoSerializer.scala:279)
        at com.romix.akka.serialization.kryo.KryoSerializer.fromBinary(KryoSerializer.scala:135)

**Comment by mklosi** [comment]
im registering all my classes upon serialization with scala i have "serialization required" true. and it serializes fine. but when deserializing on another machine that runs java, i get the 
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 113

im trying to figure out how to use the custom initializers and give them a try.
