### ISSUE TITLE
not clear how to set the kryo-initializer in the config

### ISSUE THREAD

**Issue by Zhen-hao** [altoo-ag/akka-kryo-serialization#202]
I put 
```
akka-kryo-serialization.kryo-initializer = "com.esotericsoftware.kryo.serializers.TaggedFieldSerializer"
```
in my config file. but got
```
[error] java.lang.IllegalStateException: Configured class class com.esotericsoftware.kryo.serializers.TaggedFieldSerialize
r does not extend DefaultKryoInitializer
```
Maybe I didn't understand it from the doc. Do I need to create a class in my source code?

**Comment by nvollmar** [comment]
`akka-kryo-serialization.kryo-initializer` expects an KryoInitializer (extending the `DefaultKryoInitializer`) to do your custom initialization.

If you want to change the field serializer you need to create. your `XyzKyroInitializer` extending `DefaultKryoInitializer` and then override `preInit` method:

```
class XyzKyroInitializer extends DefaultKryoInitializer {
  def preInit(kryo: ScalaKryo): Unit = {
    kryo.setDefaultSerializer(classOf[com.esotericsoftware.kryo.serializers.TaggedFieldSerializer[_]])
  }
}
```

**Comment by Zhen-hao** [comment]
Thank you so much! 
feel free to close it since there is a work in progress
