### ISSUE TITLE
Is rolling update from 0.5.2 to 1.1.0 possible?

### ISSUE THREAD

**Issue by YikSanChan** [altoo-ag/akka-kryo-serialization#208]
@nvollmar  In the application I am working on, we use kryo to (de)serialize cross-node messages inside an akka cluster. I am wondering if the implementation guarantees the backward compatibility in terms of message format such that we're possible to do a rolling update? (assuming we make correct config change)

Thank you.

**Comment by danischroeter** [comment]
@YikSanChan since 0.5.0 and onward kryo-4.0 is used so this should work - given like you said the configuration matches.
I would still recommend heavy testing though ;)

Would be interesting to know if it works for you.

**Comment by YikSanChan** [comment]
we did 0.5.2 to 1.0.0 and it works fine.
