### ISSUE TITLE
Update akka community page

### ISSUE THREAD

**Issue by patriknw** [altoo-ag/akka-kryo-serialization#23]
You might want to update the community page with some more info.
http://akka.io/community/

**Comment by spaced** [comment]
we should add badge
[![Latest version](https://index.scala-lang.org/<organization>/<repository>/<artifact>/latest.svg)](https://index.scala-lang.org/<organization>/<repository>/<artifact>)
see https://github.com/scalacenter/scaladex/wiki/FAQ

**Comment by danischroeter** [comment]
I guess we can tick this off now...
* Tags added and it's properly indexed now https://index.scala-lang.org/altoo-ag/akka-kryo-serialization/akka-kryo-serialization
* badge added https://index.scala-lang.org/altoo-ag/akka-kryo-serialization/akka-kryo-serialization/latest.svg ![i](https://index.scala-lang.org/altoo-ag/akka-kryo-serialization/akka-kryo-serialization/latest.svg) (but it takes some time until github reverse proxy is up to date...)
