### ISSUE TITLE
Hibernate proxy problem

### ISSUE THREAD

**Issue by Emmenemoi** [altoo-ag/akka-kryo-serialization#250]
It's nearly impossible to solve Hibernate proxy (or any similar java proxy) compatibility without access to a custom class resolver.

Could you add a possibility to setup a custom classresolver? Either with fully qualified class name in akka conf or through Kryo initializer?

**Comment by nvollmar** [comment]
This would have to be done by a FQCN in the config since Kryo requires the class resolver to be instantiated.

If you'd be willing to create a pull request we will take that into careful consideration.
