### ISSUE TITLE
Akka 2.5 compat

### ISSUE THREAD

**Issue by gael-ft** [altoo-ag/akka-kryo-serialization#256]
Hello,

I can see that the library (say v2.1.0) is compatible with Akka 2.5.
But when I am trying to use it i got the following message:

```
You are using version 2.6.12 of Akka, but it appears you (perhaps indirectly) also depend on older versions of related 
artifacts. You can solve this by adding an explicit dependency on version 2.6.12 of the [akka-persistence, akka-cluster-
sharding, akka-discovery, akka-protobuf, akka-actor-typed, akka-coordination, akka-slf4j, akka-persistence-typed, akka-
remote, akka-cluster-sharding-typed, akka-cluster, akka-distributed-data, akka-stream, akka-cluster-typed, akka-actor-
testkit-typed, akka-testkit, akka-cluster-tools, akka-stream-typed] artifacts to your project. See also: https://doc.akka.io
/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed
```

Am I missing something ?

**Comment by nvollmar** [comment]
We test it for compatibility against Akka 2.5, but the library comes with dependencies to Akka 2.6.
You’d have to exclude this transitive dependency when importing akka-kryo-serialization to use it with Akka 2.5

**Comment by gael-ft** [comment]
Yeah of course,

`dependencyOverrides` does the trick for the sbt conflict manager.

Sorry for inconvenience, and thanks for quick answer
