### ISSUE TITLE
Dead link to configuration in README

### ISSUE THREAD

**Issue by PawelLipski** [altoo-ag/akka-kryo-serialization#260]
In `Configuration of akka-kryo-serialization` section:
 https://github.com/altoo-ag/akka-kryo-serialization/blob/master/src/main/resources/reference.conf

Tip: see https://github.com/VirtusLab/git-machete-intellij-plugin/blob/develop/scripts/validate-markdown-links + https://github.com/VirtusLab/git-machete-intellij-plugin/blob/develop/Dockerfile#L50 for a systematic CI check ;)

**Comment by nvollmar** [comment]
Thanks for bringing this up 👍
