### ISSUE TITLE
NoSuchMethodError: io.altoo.akka.serialization.kryo.serializer.scala.ScalaKryo.setOptimizedGenerics(Z)V

### ISSUE THREAD

**Issue by mronfire** [altoo-ag/akka-kryo-serialization#269]
Hey, I am trying to use `akka-kryo-serialization-typed_2.13` (version: 2.2.0) to serialize my messages. I was having an issue where one of my messages uses `Collections.emptyList()` and it wasn't able to deserialize it, so I followed some advised on having to register the class first in CustomInitializer. I did that, and I don't get the warn message anymore - this time I get the below error message:

![image](https://user-images.githubusercontent.com/19310047/128932970-4544cf71-8426-4555-8b2d-096718625bcd.png)

I tried to set this method to false via in my initializer but that method doesn't seem to exist. Any advise on what to do for this?

**Comment by nvollmar** [comment]
Hi, the `setOptimizedGenerics` method was added in Kryo 5, please verify you have the correct version of kryo in your classpath

**Comment by mronfire** [comment]
Hey @nvollmar I have found the error I was making in my application.conf.. I had `akka-kryo-serialization` inside my `akka.actor` and it was not reaching every time I ran my project. Now, I have moved it outside `akka.actor` and it works perfectly - also using `id-strategy = "automatic"`. 
When I want to change the `id-strategy = "explicit"`, I have to register a bunch of classes used internally mostly for ActorRefs it seems like.
I was wondering, if there is a way to just register `akka.typed.ActorRef.class` all at once and thus covering all the internal classes within it.

**Comment by nvollmar** [comment]
Usually `automatic` is a good choice if the additional overhead is acceptable, classes used often in messages can then be explicitly registered to further optimize.

For using `explicit` you can check the `resolve-subclass` setting: https://github.com/altoo-ag/akka-kryo-serialization#resolving-subclasses

**Comment by mronfire** [comment]
As far as the overhead if using `automatic` as the strategy-id, how can I calculate the overhead so I can compare it with `explicit`?
I am still trying to use `explicit` to see if we can optimize the performance a bit more, and even with `resolve-subclasses` set to `true`, I keep getting errors as there is a class that needs to be registered and I have added quite a few now.. not sure how many classes it will make me have to register at this point.. just pointing that out
![image](https://user-images.githubusercontent.com/19310047/129909695-ae0795c5-4a98-45ae-9cfb-e4c25503d06b.png)

**Comment by danischroeter** [comment]
Issue seems stale - feel free to repopen if not.
