### ISSUE TITLE
Unnecessary instantiation of `clazz` if `includeManifest` is disabled in `KryoSerializerBackend`

### ISSUE THREAD

**Issue by hveiga** [altoo-ag/akka-kryo-serialization#289]
Hello,

I am debugging an issue with Kryo deserialization using Artery and `includeManifest` is set to false. When deserializing any object I can find that `manifest` is `""` and therefore `clazz` always becomes a `Failure(ClassNotFoundException(""))` since it cannot find a proper class for the value `""`. Since our system is network-heavy, we are seeing this consuming more CPU than expected (throwing exception is usually expensive and should be avoided if possible):

<img width="1782" alt="Screen Shot 2023-07-14 at 11 41 02 AM" src="https://github.com/altoo-ag/akka-kryo-serialization/assets/1147034/0f021695-61cc-4740-9983-4e8647d7633f">

The actual issue seems to be here:

https://github.com/altoo-ag/akka-kryo-serialization/blob/c5b2ed24bece3fd00275eef6d8364ad1f54837b6/akka-kryo-serialization/src/main/scala/io/altoo/akka/serialization/kryo/KryoSerializerBackend.scala#L74-L84

I am happy to open a PR to solve the issue once I get confirmation this should be changed.

**Comment by danischroeter** [comment]
Hi @hveiga 
Your absolutely right - clazz should be initialized only within the if clause! Good catch.
Would be nice if you could supply a PR. Thx!

**Comment by hveiga** [comment]
I'll do it shortly, thanks for the confirmation!

**Comment by hveiga** [comment]
Thanks for responding and merging so quick, greatly appreciated. Could we get this change released on 2.5.1 some time soon?

**Comment by danischroeter** [comment]
Thx for finding the issue - this benefits everybody...
I guess we'll create a bugfix for this one right away - should be in maven central by tomorrow...
