### ISSUE TITLE
Should `ScalaObjectSerializer` be configured to be an immutable copying serializer?

### ISSUE THREAD

**Issue by sageserpent-open** [altoo-ag/akka-kryo-serialization#297]
This has come up (and is worked around) [here](https://github.com/sageserpent-open/curium/blob/a8245d46776bd11182ac96132d64c3ec9e4f030b/src/main/scala/com/sageserpent/curium/ImmutableObjectStorageImplementation.scala#L65).

For context, the Curium project uses Kryo to perform incremental serialization and deserialization of dags of immutable Scala objects. Sometimes these refer to standalone or companion objects.

Without the aforementioned workaround, the test suite `com.sageserpent.curium.ImmutableObjectStorageSpec` fails in several tests, in particular [this one](https://github.com/sageserpent-open/curium/blob/a8245d46776bd11182ac96132d64c3ec9e4f030b/src/test/scala/com/sageserpent/curium/ImmutableObjectStorageSpec.scala#L612).

Jemmying the serializer to be immutable causes the default implementation of `copy` to yield a reference to the original standalone or companion Scala object.

While it is not the case that all such standalone / companion Scala objects are immutable, the effect is to always reference the same instance when copying an object graph, which is OK for genuinely immutable objects because of referential transparency and seems reasonable for objects that allow internal mutation, simply because that's what the original object graph would have done anyway prior to copying.

This change wouldn't affect `write` and `read`.

**Comment by danischroeter** [comment]
Hi @sageserpent-open 

If I understand your case correctly then you might want to change your dependency to https://github.com/altoo-ag/scala-kryo-serialization (akko-kryo... and pekko-kryo-serialization use this as a base) since you do not seem to use akka.
Could you open a pull request there if necessary pls? Changing the `ScalaObjectSerializer` to immutable seems fine.

There is also more documentation in https://github.com/altoo-ag/scala-kryo-serialization/blob/main/README.md on how to customize. This might also help.

**Comment by sageserpent-open** [comment]
Thanks for your response, @danischroeter.

As it happens, Curium already depends directly on this project via:
`libraryDependencies += "io.altoo"   %% "akka-kryo-serialization" % "2.4.3",`
rather than pull in the whole Akka stack. I was after a replacement for Chill as that hadn't kept up with Kryo upgrades.

I'll raise a pull request presently...

**Comment by sageserpent-open** [comment]
Sorry - I didn't read the small print carefully enough - you mean, change the dependency to:

libraryDependencies += "io.altoo"   %% "scala-kryo-serialization" % "2.4.3",

I'll do that too, and raise the PR in the right place. 😄

**Comment by sageserpent-open** [comment]
(Out of curiosity, what is the relationship between the two projects? It seems that `akka-kryo-serialization` is to some extent a source duplicate of `scala-kryo-serialization`, rather than depending on it in the sense of pulling it in as a Maven dependency.)

**Comment by nvollmar** [comment]
akka-kryo-serialization was the initial project. 
We later forked it for Pekko. As we had users using it for plain Scala projects (not using Pekko), we extracted the basic Scala serialization part into scala-kryo-serialization for those users and made pekko-kryo-serialization an extension of it.

As there wasn't much activity around the Akka version and we stopped using it ourself, we didn't actively maintain akka-kryo-serialization anymore and therefore also not made an effort to update it and use scala-kryo-serialization as base.

**Comment by sageserpent-open** [comment]
Ah, I see - when I started using `akka-kryo-serialization`, this was around about when Akka changed its license. I imagine `scala-kryo-serialization` wasn't around then, hence my confusion.

Thanks for clearing this up, @nvollmar.

I'll close this ticket as it is in the wrong repository and raise the PR in the right place.
