### ISSUE TITLE
serialize & unserialize scala xml object failed

### ISSUE THREAD

**Issue by MiloXia** [altoo-ag/akka-kryo-serialization#49]
Hi
I use akka-kryo-serialization_2.10 to serialize & unserialize scala xml(scala.xml.Elem) object， but failed.
no Exception, I can serialize xml to bytes, but cannot unserialize bytes  to xml.
the original xml object: <p>xxxx<a href="hh.com"></a><span></span></p>
the unserialize result is : List(null)

**Comment by danischroeter** [comment]
cleaning up...
this issue seems outdated - please open a new issue if still relevant...
