### ISSUE TITLE
It would be useful if compiled version 0.3.3 with scala is published

### ISSUE THREAD

**Issue by yousef-fadila** [altoo-ag/akka-kryo-serialization#51]
We wanna use the default version which is not supported with 0.3.2! the last version displayed with scala 2.10 
http://search.maven.org/#browse|-1023511903 
 It would be useful if compiled version 0.3.3 with scala 2.10 is published ...

  # default - slowest and produces bigger serialized representation. Contains fully-
  # qualified class names (FQCNs) for each class. Note that selecting this strategy
   # does not work in version 0.3.2, but is available on master and from 0.3.3 onward.

**Comment by romix** [comment]
@luben Do you happen to know how to generate both 2.10 and 2.11 versions using the same sbt file? It we would be able to build both, I could try to publish a 2.10 version in addition to the 2.11...

**Comment by luben** [comment]
Try:

+publish

It should do it for both scala-2.11 and scala-2.10

**Comment by danischroeter** [comment]
outdated - multi version build in place - next version will build against 2.11,2.12 and 2.13
