### ISSUE TITLE
java.lang.Exception: Couldn't acquire object in 5000 milliseconds.

### ISSUE THREAD

**Issue by yousef-fadila** [altoo-ag/akka-kryo-serialization#52]
In a scenario that one class is not registered, (working in explicit policy) we got the exception "class is not registered.."  16 times (exactly the number of  serializer-pool-size) and then all kryo operations failed on Couldn't acquire object in 5000 milliseconds.

It looks once the "class is not registered" exception occur, the code doesn't release the the object to ObjectPool.

**Comment by nvollmar** [comment]
is this issue still relevant with current version?

**Comment by nvollmar** [comment]
closing the issue for the time being
