### ISSUE TITLE
[Question] Does serialization also serializes the internal implementation of an Akka message ?

### ISSUE THREAD

**Issue by hajime-moto** [altoo-ag/akka-kryo-serialization#73]
Will serializing the following `case class` as Akka message with Kryo also serialize the internal implementation of this `Class` or just the `id` and `userName` get serialized ? 

``` scala
case class CreateUserCommand(id: String, userName: String) {
    val validateCommandClientSide = List(ErrorMessage("test error"))

    def validateInternalState(oldState: State) = List(ErrorMessage("test error"))

    def getEvent = UserCreated(email, password)
  }
```

**Comment by luben** [comment]
It will serialize only the data fields, i.e. "id",  "userName" and "validateCommandClientSide" AFAIK
