### ISSUE TITLE
Unit does not equal Unit after a roundtrip

### ISSUE THREAD

**Issue by aakoshh** [altoo-ag/akka-kryo-serialization#89]
If a message contains a `Unit` value, for example `() -> "Hello"`, or as part of a case class field, then while the data is properly received, Kryo seems to create another instance of `Unit` and the two message objects do not equal (and fail to pattern match), even though their `hashCode`s are the same.

The following seems to have solved the problem:

```
class KryoInit {
  def customize(kryo: Kryo) = {
    kryo.register(classOf[scala.runtime.BoxedUnit], new UnitSerializer())
  }
}

class UnitSerializer extends Serializer[Unit] {
  def write(kryo: Kryo, output: Output, obj: Unit): Unit = {
    // Write nothing, similarly to ScalaObjectSerializer
  }
  def read(kryo: Kryo, input: Input, typ: Class[Unit]): Unit = {
    // Return the one true Unit
    () 
  }
}
```

I was wondering if this should be part of the base set of Scala serialisers.

**Comment by TimSoethout** [comment]
Just ran into the same thing:

```
  "Unit" should "preserve () equality" in {
    val unit: Unit = roundTrip(1, ())
    assert(unit == ())
  }
```

results in:
```
<(), the Unit value> did not equal <(), the Unit value>
ScalaTestFailureLocation: com.romix.scala.serialization.kryo.SpecCase at (SpecCase.scala:38)
org.scalatest.exceptions.TestFailedException: <(), the Unit value> did not equal <(), the Unit value>
```

Same holds for `BoxedUnit`:
```
  "BoxedUnit" should "preserve () equality" in {
    val unit: BoxedUnit = roundTrip(1, BoxedUnit.UNIT)
    assert(unit == BoxedUnit.UNIT)
  }
```

Chill seems to have a solution:
https://github.com/xitrum-framework/chill-scala/blob/master/src/main/scala/com/twitter/chill/ScalaKryoInstantiator.scala#L195

**Comment by TimSoethout** [comment]
```scala
  class BoxedUnitSerializer extends Serializer[BoxedUnit] {
    override def write(kser: Kryo, out: Output, obj: BoxedUnit): Unit = {}
    override def read(kser: Kryo, in: Input, cls: Class[BoxedUnit]): BoxedUnit = BoxedUnit.UNIT
  }
```
with
```scala
 kryo.addDefaultSerializer(classOf[BoxedUnit], new BoxedUnitSerializer)
```
Seems to work for the `(roundTrip(())`.

Although it does give me back the NPE from #100, when nested in a `Validated`. Will try to reproduce this in @ktoso's example.

**Comment by TimSoethout** [comment]
It seems the line`kryo.getFieldSerializerConfig.setOptimizedGenerics(true)` breaks this. Without this (with the default of `false`) it seems to work as expected.

**Comment by luben** [comment]
I combined @aakoshh proposed solution and @TimSoethout tests. It's already in master. We should get v0.4.2 pretty soon with the Unit identity fixed and the same code but compiled against Kryo-4.0 as v0.5.0.

**Comment by spaced** [comment]
v0.4.2 is released.
